"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, Camera, Check, Eye, EyeOff, ImagePlus } from "lucide-react";

type ProfileDraft = { name: string; email: string; birthDate: string; sex: string; phone: string; photo?: string };

export default function Cadastro() {
  const router = useRouter();
  const fileRef = useRef<HTMLInputElement>(null);
  const [next, setNext] = useState("/entrar");
  const [show, setShow] = useState(false);
  const [done, setDone] = useState(false);
  const [error, setError] = useState("");
  const [photo, setPhoto] = useState("");
  useEffect(() => { const value = new URLSearchParams(window.location.search).get("next"); if (value?.startsWith("/")) setNext(value); }, []);
  function choosePhoto(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (!file.type.startsWith("image/")) { setError("Escolha um arquivo de imagem válido."); return; } if (file.size > 4 * 1024 * 1024) { setError("A foto deve ter no máximo 4 MB."); return; } const reader = new FileReader(); reader.onload = () => setPhoto(String(reader.result)); reader.readAsDataURL(file); }
  function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const form = new FormData(event.currentTarget); const password = String(form.get("password")); if (password.length < 10) { setError("Sua senha precisa ter pelo menos 10 caracteres."); return; } const profile: ProfileDraft = { name: String(form.get("name") || ""), email: String(form.get("email") || ""), birthDate: String(form.get("birthDate") || ""), sex: String(form.get("sex") || ""), phone: String(form.get("phone") || ""), photo }; window.localStorage.setItem("pqa-demo-session", JSON.stringify(profile)); setDone(true); window.setTimeout(() => router.replace(next), 700); }
  return <main className="auth-shell auth-road-shell"><div className="auth-card auth-profile-card"><Link href="/" className="back-link"><ArrowLeft size={16} /> Voltar para o início</Link>{done ? <><div className="success-icon"><Check /></div><div className="eyebrow">Conta criada com sucesso</div><h1>Vamos para a sua jornada.</h1><p className="muted">Seu acesso foi criado. Você será encaminhado para a pré-inscrição em instantes.</p></> : <><div className="eyebrow">Primeiro passo · seu perfil</div><h1>Crie sua conta</h1><p className="muted">Preencha seus dados para acompanhar cada ponto da corrida.</p><form onSubmit={submit}><div className="profile-photo-field"><button type="button" className={`profile-photo ${photo ? "has-photo" : ""}`} onClick={() => fileRef.current?.click()} aria-label="Escolher foto do participante">{photo ? <img src={photo} alt="Prévia da sua foto" /> : <><ImagePlus size={26} /><span>Adicionar foto</span><small>Opcional</small></>}</button><input ref={fileRef} className="visually-hidden" type="file" accept="image/*" onChange={choosePhoto} /><div><strong>Foto do participante</strong><p>Use uma foto para personalizar sua jornada.</p><button type="button" className="photo-adjust" onClick={() => fileRef.current?.click()}><Camera size={15} /> Ajustar foto</button></div></div><label>Nome completo<input name="name" required minLength={3} maxLength={120} placeholder="Como podemos chamar você?" /></label><div className="form-two-cols"><label>Data de nascimento<input name="birthDate" type="date" required /></label><label>Sexo<select name="sex" required defaultValue=""><option value="" disabled>Selecione</option><option value="female">Feminino</option><option value="male">Masculino</option><option value="non-binary">Não binário</option><option value="prefer-not">Prefiro não informar</option></select></label></div><label>Telefone<input name="phone" type="tel" required placeholder="(00) 00000-0000" /></label><label>E-mail<input name="email" type="email" required placeholder="voce@email.com" /></label><label>Senha<div className="password-wrap"><input name="password" type={show ? "text" : "password"} required minLength={10} placeholder="Mínimo de 10 caracteres" /><button type="button" aria-label={show ? "Ocultar senha" : "Mostrar senha"} onClick={() => setShow(!show)}>{show ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></label><label className="checkline"><input type="checkbox" required /> <span>Li e aceito o <Link href="/privacidade">Aviso de Privacidade</Link> para criar minha conta.</span></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="button button-primary" type="submit">Criar minha conta</button></form><p className="switch">Já tem uma conta? <Link href={`/entrar?next=${encodeURIComponent(next)}`}>Entrar</Link></p></>}</div></main>;
}
