create extension if not exists pgcrypto;

create type public.sex_type as enum ('FEMALE','MALE','OTHER','PREFER_NOT_TO_SAY');
create type public.registration_status as enum ('DRAFT','AWAITING_GUARDIAN_CONSENT','PRE_REGISTERED','DONATION_RECEIVED','CONFIRMED');
create type public.consent_type as enum ('PRIVACY_NOTICE','IMAGE_AND_VOICE_AUTHORIZATION','MARKETING');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null check (char_length(full_name) between 3 and 120), phone_e164 text, sex public.sex_type, birth_date date, avatar_path text, profile_completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.events (id uuid primary key default gen_random_uuid(), slug text not null unique, name text not null, event_date date not null, location text not null, distance_km numeric(5,2) not null, status text not null default 'OPEN', donation_instructions text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.consent_documents (id uuid primary key default gen_random_uuid(), type public.consent_type not null, version text not null, title text not null, body_markdown text not null, content_sha256 text not null, effective_at timestamptz not null, active boolean not null default true, created_at timestamptz not null default now(), unique(type, version));
create table public.consent_acceptances (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete restrict, document_id uuid not null references public.consent_documents(id) on delete restrict, accepted boolean not null, typed_name text not null, accepted_at timestamptz, revoked_at timestamptz, session_id text, ip_hmac text, user_agent text, document_hash text not null, guardian_id uuid, created_at timestamptz not null default now());
create table public.guardians (id uuid primary key default gen_random_uuid(), participant_user_id uuid not null references auth.users(id) on delete restrict, full_name text not null, email text not null, phone_e164 text, relationship text not null, verification_token_hash text not null, token_expires_at timestamptz not null, verified_at timestamptz, created_at timestamptz not null default now());
create table public.registrations (id uuid primary key default gen_random_uuid(), protocol text not null unique, event_id uuid not null references public.events(id) on delete restrict, user_id uuid not null references auth.users(id) on delete restrict, referral_source text not null check (referral_source in ('REFERRAL','MF_CONTABILIDADE','MF_PARTNERS')), referrer_name text, shirt_size text not null check (shirt_size in ('P','M','G','GG')), status public.registration_status not null default 'DRAFT', submitted_at timestamptz, guardian_confirmed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(event_id,user_id), check ((referral_source = 'REFERRAL' and referrer_name is not null and char_length(referrer_name) between 2 and 120) or (referral_source <> 'REFERRAL' and referrer_name is null)));
create table public.webhook_deliveries (id uuid primary key default gen_random_uuid(), registration_id uuid not null references public.registrations(id) on delete cascade, event_type text not null, idempotency_key uuid not null unique, payload_hash text not null, status text not null default 'PENDING', attempts integer not null default 0, last_http_status integer, last_error_sanitized text, delivered_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create index registrations_user_idx on public.registrations(user_id); create index registrations_event_idx on public.registrations(event_id); create index registrations_status_idx on public.registrations(status); create index registrations_submitted_idx on public.registrations(submitted_at); create index webhook_idempotency_idx on public.webhook_deliveries(idempotency_key);
create unique index consent_one_active_per_type on public.consent_documents(type) where active;

alter table public.profiles enable row level security; alter table public.events enable row level security; alter table public.consent_documents enable row level security; alter table public.consent_acceptances enable row level security; alter table public.guardians enable row level security; alter table public.registrations enable row level security; alter table public.webhook_deliveries enable row level security;
create policy "own profile select" on public.profiles for select using (auth.uid() = id); create policy "own profile insert" on public.profiles for insert with check (auth.uid() = id); create policy "own profile update" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);
create policy "public event read" on public.events for select using (status = 'OPEN'); create policy "active documents read" on public.consent_documents for select using (active);
create policy "own acceptances read" on public.consent_acceptances for select using (auth.uid() = user_id); create policy "own acceptance insert" on public.consent_acceptances for insert with check (auth.uid() = user_id and revoked_at is null);
create policy "own guardian read" on public.guardians for select using (auth.uid() = participant_user_id); create policy "own registration read" on public.registrations for select using (auth.uid() = user_id); create policy "own registration insert" on public.registrations for insert with check (auth.uid() = user_id and status = 'DRAFT');

create or replace function public.prevent_acceptance_mutation() returns trigger language plpgsql as $$ begin raise exception 'consent audit records are immutable'; end; $$;
create trigger consent_immutable before update or delete on public.consent_acceptances for each row execute function public.prevent_acceptance_mutation();
create or replace function public.confirm_pre_registration(p_event_id uuid, p_user_id uuid, p_referral_source text, p_referrer_name text, p_shirt_size text) returns public.registrations language plpgsql security definer set search_path=public as $$
declare r public.registrations; profile_row public.profiles; missing_count integer;
begin
 if auth.uid() is null or auth.uid() <> p_user_id then raise exception 'unauthorized'; end if;
 select * into profile_row from profiles where id=p_user_id;
 if profile_row.profile_completed_at is null or not exists(select 1 from auth.users where id=p_user_id and email_confirmed_at is not null) then raise exception 'profile_or_email_incomplete'; end if;
 select count(*) into missing_count from consent_documents d where d.active and d.type in ('PRIVACY_NOTICE','IMAGE_AND_VOICE_AUTHORIZATION') and not exists(select 1 from consent_acceptances a where a.user_id=p_user_id and a.document_id=d.id and a.accepted and a.revoked_at is null);
 if missing_count > 0 then raise exception 'current_consents_missing'; end if;
 insert into registrations(protocol,event_id,user_id,referral_source,referrer_name,shirt_size,status,submitted_at) values ('PQA-'||extract(year from (select event_date from events where id=p_event_id))||'-'||upper(substr(encode(gen_random_bytes(5),'hex'),1,8)),p_event_id,p_user_id,p_referral_source,p_referrer_name,p_shirt_size,'PRE_REGISTERED',now()) returning * into r;
 return r;
exception when unique_violation then raise exception 'registration_already_exists';
end; $$;
